spring:
  datasource:
    url: jdbc:mysql://localhost:3306/note-share?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh&useSSL=false
    username: root
    password: 1234
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid
  data:
    redis:
      host: localhost
      database: 0
      port: 6379
      password:
      timeout: 300ms
logging:
  level:
    root: info
    com.dinhhuan.note: debug
    org:
      apache:
        ibatis: DEBUG
    com:
      dinhhuan:
        note:
          mapper: DEBUG
logstash:
  host: localhost
  enableInnerLog: false
minio:
  endpoint: https://biz.dinhhuan.id.vn
  username: minioadmin
  password: minioadmin
  bucket: note-app